apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec: # Add this line  dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: worker-2
      tolerations:
      - key: "node-role.kubernetes.io/worker"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        env:
        - name: PMA_HOST
          value: "10.101.99.126" # MySQL clusterIP
        - name: PMA_PORT
          value: "3306"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-registry-key

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30000 # You can specify any available port number
